-- Buddy corpus Phase 2: high-priority Nigerian topics missing from Phase 1 —
-- sickle cell, HIV/STIs, TB, hepatitis B, newborn care, anaemia, chronic-condition
-- self-management, snakebite, worms. Sourced WHO/NHS. reviewed defaults false —
-- the GP signs these off (see Buddy Corpus Phase 2 review doc) before reliance.
INSERT INTO buddy_sources (slug, topic, title, body, source_name, source_url) VALUES
('sickle-cell','sickle cell','Sickle cell disease','Sickle cell disease is an inherited condition where red blood cells become sickle-shaped and can block blood flow, causing episodes of pain called crises. Drinking plenty of water, avoiding extreme cold or heat, resting, and taking prescribed medicines can reduce crises. Seek urgent care for severe pain, high fever, breathing difficulty, or swelling of the hands or feet.','WHO','https://www.who.int/news-room/fact-sheets/detail/sickle-cell-disease'),
('genotype-awareness','sickle cell','Know your genotype','Sickle cell disease is passed from parents to children. Knowing your genotype (for example AA, AS or SS) helps you understand the risk before having children. A simple blood test at a clinic shows your genotype; couples planning marriage or children are encouraged to check and get counselling.','WHO','https://www.who.int/news-room/fact-sheets/detail/sickle-cell-disease'),
('hypertension-management','blood pressure','Living with high blood pressure','If you have high blood pressure, take your medicine every day as prescribed — even when you feel fine, because it often has no symptoms. Eat less salt, stay active, avoid smoking, and have your blood pressure checked regularly. Do not stop your medicine without talking to a clinician.','WHO','https://www.who.int/news-room/fact-sheets/detail/hypertension'),
('diabetes-management','diabetes','Living with diabetes','If you have diabetes, take your medicine as prescribed, eat balanced meals, stay active, and check your feet daily for sores. Learn the signs of very low sugar (shaking, sweating, confusion) and very high sugar (great thirst, frequent urination), and seek care if they occur or do not improve.','NHS','https://www.nhs.uk/conditions/type-2-diabetes/'),
('hiv-basics','hiv','HIV — testing and treatment','HIV is a virus spread mainly through unprotected sex, infected blood, and from mother to baby. There is no cure, but daily medicine (ART) keeps people healthy and can stop the virus passing to others. Get tested to know your status — testing and treatment are free at many centres — and condoms reduce the risk.','WHO','https://www.who.int/news-room/fact-sheets/detail/hiv-aids'),
('stis','sexual health','Sexually transmitted infections (STIs)','STIs can cause discharge, sores, itching or pain when passing urine — but sometimes there are no symptoms. Most are treatable, especially when caught early. If you notice symptoms or have had unprotected sex, visit a clinic for testing and treatment, and use condoms to lower the risk.','WHO','https://www.who.int/news-room/fact-sheets/detail/sexually-transmitted-infections-(stis)'),
('tuberculosis','tuberculosis','Tuberculosis (TB)','Tuberculosis mainly affects the lungs and spreads through the air when an infected person coughs. A cough lasting more than two weeks — especially with fever, night sweats, weight loss or coughing blood — may be TB. TB is curable with a full course of treatment, so go to a health centre for a test; testing and treatment are usually free.','WHO','https://www.who.int/news-room/fact-sheets/detail/tuberculosis'),
('hepatitis-b','hepatitis','Hepatitis B','Hepatitis B is a virus that affects the liver and is common in Nigeria. It spreads through infected blood and body fluids and from mother to baby. A safe vaccine prevents it, and infected people can be monitored and treated. Ask about testing and vaccination at a clinic, especially for newborns and family members.','WHO','https://www.who.int/news-room/fact-sheets/detail/hepatitis-b'),
('newborn-care','child health','Newborn care & danger signs','A newborn needs to be kept warm, breastfed early and often (only breast milk for the first 6 months), and have the cord kept clean and dry. Take the baby to a health facility straight away for danger signs: not feeding, fever or a cold body, fast or difficult breathing, yellow skin or eyes, or fits.','WHO','https://www.who.int/news-room/fact-sheets/detail/newborn-health'),
('anaemia-pregnancy','pregnancy','Anaemia in pregnancy','Anaemia (low blood) is common in pregnancy and can make you tired, weak and breathless. Iron and folic acid tablets from antenatal care, plus iron-rich foods like beans, green vegetables and liver, help prevent it. Attend antenatal visits and take the supplements as advised.','WHO','https://www.who.int/health-topics/anaemia'),
('snakebite-first-aid','first aid','Snakebite first aid','After a snakebite, stay calm and keep the bitten limb still and lower than the heart to slow the venom. Remove tight clothing or jewellery, and get to a hospital as fast as possible for antivenom. Do not cut the wound, suck out venom, apply a tight tourniquet, or use herbs.','WHO','https://www.who.int/news-room/fact-sheets/detail/snakebite-envenoming'),
('intestinal-worms','hygiene','Intestinal worms','Intestinal worms are common and spread through contaminated food, water and soil. They can cause stomach pain, tiredness and poor growth in children. Wash hands and food, wear shoes, and take deworming medicine as recommended (often every six months for children). See a clinic if symptoms persist.','WHO','https://www.who.int/news-room/fact-sheets/detail/soil-transmitted-helminth-infections')
ON CONFLICT (slug) DO NOTHING;
