-- ───────────────────────────────────────────────────────────────────────────
-- Buddy corpus expansion — run-in-Supabase-SQL-Editor edition (migration 037)
-- ───────────────────────────────────────────────────────────────────────────
-- Adds high-frequency Nigerian health topics (malaria PREVENTION, antenatal,
-- immunisation, family planning, typhoid, hygiene, first aid, nutrition) so the
-- Buddy stops punting on common questions. Sourced WHO/NHS/CDC. Idempotent.
-- NOTE: reviewed=false — clinician should sign these off.

INSERT INTO buddy_sources (slug, topic, title, body, source_name, source_url) VALUES
('malaria-prevention','malaria','Preventing malaria','Malaria is preventable. Sleeping under an insecticide-treated net every night is one of the best protections, especially for children and pregnant women. Cut down mosquito breeding by clearing stagnant water around the home, and use repellent in the evening. If fever starts, get a malaria test quickly so treatment can begin early.','WHO','https://www.who.int/news-room/fact-sheets/detail/malaria'),
('malaria-pregnancy','malaria','Malaria in pregnancy','Malaria in pregnancy is dangerous for both mother and baby. Pregnant women should sleep under an insecticide-treated net and attend antenatal care, where preventive treatment and testing are offered. Get any fever checked quickly at a clinic.','WHO','https://www.who.int/news-room/fact-sheets/detail/malaria'),
('antenatal-care','pregnancy','Antenatal (pregnancy) care','Antenatal care helps keep mother and baby healthy. Start visits early in pregnancy and attend regularly, where you get check-ups, malaria and tetanus prevention, iron and folic acid, and advice. Go sooner if you notice any warning sign.','WHO','https://www.who.int/health-topics/maternal-health'),
('pregnancy-danger-signs','pregnancy','Pregnancy danger signs','Some pregnancy symptoms need urgent care. Go to a health facility straight away for vaginal bleeding, a severe headache or blurred vision, severe belly pain, strong swelling of the face or hands, fever, or if the baby stops moving. These can be serious for mother and baby.','WHO','https://www.who.int/health-topics/maternal-health'),
('childhood-immunisation','immunisation','Childhood vaccines','Routine childhood vaccines protect against serious diseases like measles, polio, tetanus and tuberculosis. Follow the national immunisation schedule and keep your child''s vaccination card up to date. Free vaccines are available at government health centres — ask the nearest clinic.','WHO','https://www.who.int/health-topics/vaccines-and-immunization'),
('family-planning','family planning','Family planning & contraception','Family planning lets people choose if and when to have children. Several safe methods exist — including pills, injectables, implants, IUDs and condoms — each with different benefits. A clinic or pharmacy can help you choose what suits you; condoms also help protect against sexually transmitted infections.','WHO','https://www.who.int/news-room/fact-sheets/detail/family-planning-contraception'),
('typhoid','typhoid','Typhoid fever','Typhoid is a bacterial infection spread through contaminated food and water, causing a lasting fever, weakness, stomach pain and headache. Safe water, good hygiene and clean food lower the risk, and vaccination is available. See a clinician for a fever that will not go — typhoid needs proper testing and antibiotics.','WHO','https://www.who.int/news-room/fact-sheets/detail/typhoid'),
('handwashing','hygiene','Handwashing','Washing hands with soap and clean water removes germs and helps prevent diarrhoea and many infections. Wash before eating or cooking and after using the toilet or cleaning a child. Where soap and water are not available, use an alcohol-based hand sanitiser.','CDC','https://www.cdc.gov/clean-hands/about/index.html'),
('safe-water-food','hygiene','Safe water & food','Unsafe water and food cause diarrhoea and typhoid. Drink water that is treated, boiled or from a safe source, and keep it covered. Wash fruits and vegetables, cook food well and eat it while still hot. These simple steps prevent many illnesses.','WHO','https://www.who.int/news-room/fact-sheets/detail/food-safety'),
('breastfeeding','child health','Breastfeeding','Breast milk is the best food for babies. WHO recommends exclusive breastfeeding — only breast milk, no water or other food — for the first 6 months, then continued breastfeeding with other foods up to 2 years. Breastfeeding protects babies from infection and supports healthy growth.','WHO','https://www.who.int/health-topics/breastfeeding'),
('child-nutrition','child health','Child nutrition','Good nutrition helps children grow and fight illness. From 6 months, give a variety of foods — such as beans, eggs, fish, fruits and vegetables — alongside breastfeeding. Seek care if a child is very thin, swollen, or not gaining weight, as this can signal malnutrition.','WHO','https://www.who.int/health-topics/nutrition'),
('first-aid-burns','first aid','First aid for burns','For a minor burn, cool it under cool or lukewarm running water for about 20 minutes as soon as possible, then cover loosely with cling film or a clean, non-fluffy cloth. Do not apply ice, butter, oil or toothpaste. Get medical care for large, deep or blistering burns, or burns to the face, hands or genitals.','NHS','https://www.nhs.uk/conditions/burns-and-scalds/'),
('first-aid-bleeding','first aid','First aid for a bleeding wound','For a bleeding wound, press firmly on it with a clean cloth and raise the area if you can. Keep pressing until the bleeding slows, then cover it with a clean dressing. Get urgent care if the bleeding is heavy, will not stop, or the wound is deep or dirty — and make sure your tetanus protection is up to date.','NHS','https://www.nhs.uk/conditions/cuts-and-grazes/'),
('cough','cough','Cough','Most coughs are caused by viral infections and clear on their own within a few weeks; rest, fluids and warm drinks can ease them, and antibiotics do not help a viral cough. See a clinician if a cough lasts more than three weeks, brings up blood, or comes with chest pain, breathlessness or weight loss.','NHS','https://www.nhs.uk/conditions/cough/')
ON CONFLICT (slug) DO NOTHING;

-- Mark migration 037 as applied so `npm run migrate` won't re-run it.
INSERT INTO _migrations (name) VALUES ('037_buddy_corpus_expansion.sql') ON CONFLICT (name) DO NOTHING;

-- Verify
SELECT count(*) AS total_sources FROM buddy_sources;
