-- Starter batch of 30 health tips, loaded as DRAFTS for admin review.
-- Run AFTER migration 071 (needs the new columns + status). Safe to re-run:
-- rows are only inserted if a tip with the same title does not already exist,
-- and every row lands as status='draft' so NOTHING sends until an admin
-- reviews it in Health Tips → Tip library and switches it to Published.
--
-- Content is general public-health guidance in the same spirit as the AI-draft
-- flow: no diagnosis, no drug names/dosages, no invented statistics, no PHI.
-- Dollar-quoted ($$...$$) so apostrophes need no escaping.

INSERT INTO health_tips (title, body, sms_text, why_it_matters, action, myth, fact, source, category, status)
SELECT v.title, v.body, v.sms_text, v.why_it_matters, v.action, v.myth, v.fact, v.source, v.category, 'draft'
FROM (VALUES
  ($$Guard against typhoid$$,
   $$Typhoid fever spreads through water and food contaminated with bacteria. Boiling or treating your drinking water, washing fruits with clean water, and eating food while it is still hot greatly lower your risk.$$,
   $$Drink only safe water and eat hot, freshly cooked food. Typhoid spreads through contaminated food and water.$$,
   $$Typhoid is common in Nigeria and can cause weeks of fever and serious complications if untreated. Most cases are preventable with safe water and careful food handling.$$,
   $$Boil or treat your drinking water today, and skip ice or drinks made with water from unknown sources.$$,
   $$A high fever always means malaria.$$,
   $$Typhoid and other infections cause the same fever; a test tells them apart so you get the right treatment.$$,
   $$Nigeria CDC$$, $$prevention$$),

  ($$Sleep under a treated net$$,
   $$Insecticide-treated nets are one of the most effective ways to prevent malaria, especially for children under five and pregnant women. Use the net every night, tuck it under the mattress, and repair any holes.$$,
   $$Sleep under an insecticide-treated net every night to keep malaria-carrying mosquitoes away.$$,
   $$Malaria is spread by night-biting mosquitoes, so a treated net protects you during the hours when most bites happen.$$,
   $$Hang and tuck in your treated net tonight, and check it for holes to patch or replace.$$,
   $$You only need a net during the rainy season.$$,
   $$Mosquitoes bite all year round in Nigeria, so using your net every night gives the best protection.$$,
   $$WHO$$, $$prevention$$),

  ($$Know your genotype$$,
   $$Your genotype shows whether you carry the sickle cell trait. If both partners are AS (carriers), each pregnancy carries a one-in-four chance of a child with sickle cell disease. A simple blood test reveals your genotype.$$,
   $$Know your genotype (AA, AS, SS) before marriage or children. Two AS partners can have a child with sickle cell.$$,
   $$Knowing your and your partner's genotype early helps couples make informed decisions and plan for their children's health.$$,
   $$If you do not know your genotype, ask for a genotype test at your nearest lab or clinic.$$,
   $$Genotype only matters if someone in your family has sickle cell.$$,
   $$Many carriers (AS) have no symptoms and no known family history, so testing is the only way to be sure.$$,
   $$Sickle Cell Foundation Nigeria$$, $$prevention$$),

  ($$Go easy on salt$$,
   $$Eating too much salt raises blood pressure, a leading cause of stroke and heart disease. Much of our salt comes from seasoning cubes, table salt and processed foods rather than from what we can taste.$$,
   $$Cut back on salt and salty seasoning cubes to help keep your blood pressure down.$$,
   $$Lowering salt is one of the simplest ways to protect your heart and kidneys, especially if your blood pressure is already high.$$,
   $$Taste your food before adding extra salt today, and use pepper, onions or garlic for flavour instead.$$,
   $$If food does not taste salty, it is low in salt.$$,
   $$Seasoning cubes, bread and processed foods hide a lot of salt you cannot taste.$$,
   $$WHO$$, $$nutrition$$),

  ($$Rethink sugary drinks$$,
   $$Soft drinks, energy drinks and sweetened juices are packed with sugar and offer little nutrition. Drinking them regularly adds up to weight gain and a higher risk of type 2 diabetes and tooth decay.$$,
   $$Swap soft drinks and sweetened juice for water. Sugary drinks add hidden sugar and raise diabetes risk.$$,
   $$Type 2 diabetes is rising fast in Nigeria, and sugary drinks are a major, avoidable contributor.$$,
   $$Replace one sugary drink with water or unsweetened zobo today.$$,
   $$$$, $$$$,
   $$WHO$$, $$nutrition$$),

  ($$Spot diabetes early$$,
   $$Type 2 diabetes often develops quietly. Warning signs include passing urine often, being unusually thirsty or hungry, tiredness, blurred vision, and wounds that heal slowly. A simple blood sugar test can catch it early.$$,
   $$Frequent urination, constant thirst, tiredness and slow-healing wounds can signal diabetes. Get a sugar test.$$,
   $$Caught early, diabetes can be managed well; left unchecked it damages the eyes, kidneys, nerves and heart.$$,
   $$If you have these signs or a family history, ask for a blood sugar test at a pharmacy or clinic this week.$$,
   $$Diabetes only affects people who are overweight.$$,
   $$Anyone can develop diabetes; family history, diet and activity all play a part.$$,
   $$Nigeria CDC$$, $$prevention$$),

  ($$Start antenatal care early$$,
   $$Early and regular antenatal care helps catch problems like high blood pressure, anaemia and infections before they become dangerous. It also provides protection such as tetanus vaccination and malaria prevention in pregnancy.$$,
   $$Pregnant? Start antenatal visits in the first three months and keep every appointment for a safer pregnancy.$$,
   $$Regular antenatal care is one of the strongest protections for both mother and baby.$$,
   $$If you or someone you know is pregnant, book the first antenatal visit at a clinic as soon as possible.$$,
   $$$$, $$$$,
   $$WHO$$, $$maternal$$),

  ($$Breastfeed for the first 6 months$$,
   $$For the first six months, breast milk gives a baby all the food and water it needs, plus antibodies that protect against diarrhoea and chest infections. Exclusive means no water, pap or other foods during this time.$$,
   $$Breast milk alone, no water, for the first 6 months gives babies the best start and protection from illness.$$,
   $$Exclusive breastfeeding lowers infant illness and supports healthy growth and brain development.$$,
   $$If you are breastfeeding, offer the breast on demand and hold off on water or other foods until six months.$$,
   $$Babies need extra water in hot weather.$$,
   $$Breast milk is mostly water and meets a baby's full fluid needs in the first six months.$$,
   $$WHO and UNICEF$$, $$maternal$$),

  ($$Keep vaccines on schedule$$,
   $$Routine childhood vaccines protect against serious diseases like measles, polio, tuberculosis, whooping cough and hepatitis B. Following the full schedule, on time, gives the strongest protection.$$,
   $$Take your child for every routine immunisation on time to protect them from measles, polio and more.$$,
   $$Vaccines prevent illnesses that once killed or disabled many Nigerian children, and they protect the whole community.$$,
   $$Check your child's immunisation card and book any missed or upcoming vaccines at the health centre.$$,
   $$If a child misses a vaccine date, you have to start all over.$$,
   $$In most cases you simply continue from where you stopped; ask the health worker to catch up missed doses.$$,
   $$WHO$$, $$prevention$$),

  ($$Store drinking water safely$$,
   $$Even safe water can become contaminated if stored openly or scooped out with hands or dirty cups. Use a clean, covered container, ideally one with a tap, and keep it off the floor.$$,
   $$Keep drinking water in a clean, covered container and draw it with a clean cup or tap, not your hands.$$,
   $$Safe storage prevents diarrhoea, cholera and typhoid, which spread easily through contaminated water.$$,
   $$Cover your water storage container today and set aside a dedicated clean cup or tap to draw from it.$$,
   $$$$, $$$$,
   $$Nigeria CDC$$, $$hygiene$$),

  ($$A long cough needs a test$$,
   $$Tuberculosis spreads through the air and often starts with a cough lasting more than two weeks, sometimes with fever, night sweats and weight loss. Testing and treatment for TB are free at government health facilities.$$,
   $$A cough lasting over two weeks, with weight loss or night sweats, could be TB. Testing is free, so get checked.$$,
   $$TB is curable, but only if diagnosed and treated fully. Early testing protects you and the people around you.$$,
   $$If you or someone at home has coughed for over two weeks, visit a health centre for a free TB test.$$,
   $$TB is a disease of the past or only affects the poor.$$,
   $$TB is still common in Nigeria and anyone can catch it, but it is preventable and curable.$$,
   $$Nigeria CDC$$, $$prevention$$),

  ($$Know your HIV status$$,
   $$Knowing your HIV status puts you in control. If negative, you learn how to stay that way; if positive, early treatment keeps you healthy and prevents passing it on. Testing is confidential and widely available.$$,
   $$Get an HIV test and know your status. Testing is confidential, and treatment lets people live long, healthy lives.$$,
   $$Modern treatment means people living with HIV can live long, full lives, but only if they know their status and start care.$$,
   $$Book a confidential HIV test at a clinic, and encourage your partner to test too.$$,
   $$You can tell if someone has HIV by looking at them.$$,
   $$People with HIV often look and feel healthy for years, so testing is the only way to know.$$,
   $$WHO$$, $$prevention$$),

  ($$Protect against hepatitis B$$,
   $$Hepatitis B is a virus that can silently damage the liver over years and is common in Nigeria. It spreads through blood and body fluids, including from mother to baby. A safe vaccine prevents it, and a test shows if you are protected.$$,
   $$Hepatitis B attacks the liver and is common in Nigeria. Ask about testing and the vaccine that prevents it.$$,
   $$Many people carry hepatitis B without knowing until the liver is badly affected, which testing and vaccination prevent.$$,
   $$Ask your clinic about a hepatitis B test and vaccine, especially if you have never been vaccinated.$$,
   $$$$, $$$$,
   $$WHO$$, $$prevention$$),

  ($$The right first aid for burns$$,
   $$For a minor burn, hold it under cool (not icy) running water for about 20 minutes, then cover loosely with a clean cloth. Do not apply toothpaste, oil, butter, egg or ice, which trap heat or raise the risk of infection.$$,
   $$For a burn, cool it under clean running water for 20 minutes. Never apply toothpaste, oil, egg or ice.$$,
   $$Quick cooling limits the damage and pain, while home remedies can make a burn worse and harder to treat.$$,
   $$Remember: cool running water first, then cover loosely. Seek care for large, deep or blistering burns.$$,
   $$Toothpaste or palm oil soothes a burn.$$,
   $$They trap heat and raise infection risk; clean running water is the only safe first step.$$,
   $$WHO$$, $$safety$$),

  ($$What to do for a snake bite$$,
   $$If someone is bitten by a snake, keep them calm and still, gently keep the bitten limb from moving, and remove tight items like rings. Get to a hospital that has antivenom as fast as possible. Do not cut the wound, suck it, tie a tourniquet, or use herbs.$$,
   $$Snake bite? Stay calm, keep the limb still, and get to a hospital fast. Do not cut, suck or tie the wound.$$,
   $$Fast hospital care with antivenom saves lives, while traditional first-aid methods often cause more harm and waste time.$$,
   $$Find out now which nearby hospital stocks antivenom, so you know where to go in an emergency.$$,
   $$Cutting or tying above a snake bite draws out the venom.$$,
   $$These delay real treatment and can cause serious injury; rapid transport to hospital is what saves lives.$$,
   $$WHO$$, $$safety$$),

  ($$Mind your mental health$$,
   $$Stress, worry and low mood affect everyone at times. Talking to someone you trust, keeping a routine, staying active and resting well all help. Lasting sadness, hopelessness or trouble coping deserve support, just like any physical illness.$$,
   $$Feeling stressed or low is common and nothing to be ashamed of. Talk to someone you trust, and rest well.$$,
   $$Mental health is part of overall health, and reaching out early makes problems easier to manage.$$,
   $$Reach out to a friend, family member or health worker if something has been weighing on you.$$,
   $$Mental health problems are a sign of weakness or a spiritual attack.$$,
   $$They are common health conditions that improve with support and, when needed, professional care.$$,
   $$WHO$$, $$mental$$),

  ($$Screen for cervical cancer$$,
   $$Cervical cancer is one of the most common cancers in Nigerian women, yet it is highly preventable. Screening can find early changes before they become cancer, and the HPV vaccine protects girls before exposure.$$,
   $$A simple cervical screening can catch changes early, before cancer develops. Ask your clinic about it.$$,
   $$Caught early through screening, cervical changes are easily treated, which is why regular screening saves lives.$$,
   $$If you are a woman aged 30 or older, ask your clinic about cervical cancer screening.$$,
   $$$$, $$$$,
   $$WHO$$, $$prevention$$),

  ($$Know your breasts$$,
   $$Being familiar with the normal look and feel of your breasts helps you notice changes early. See a health worker about any new lump, skin change or nipple discharge. Most changes are not cancer, but early checks save lives when they are.$$,
   $$Get to know how your breasts normally look and feel, and see a doctor about any new lump or change.$$,
   $$Breast cancer is far more treatable when found early, so noticing and reporting changes quickly matters.$$,
   $$Check in with how your breasts normally feel, and book a review for anything new or unusual.$$,
   $$$$, $$$$,
   $$WHO$$, $$prevention$$),

  ($$Men, mind your prostate$$,
   $$As men age, the prostate can enlarge, causing a weak urine stream, difficulty starting, or frequent night-time urination. Most causes are not cancer, but a check-up can find problems early, including prostate cancer.$$,
   $$Men over 40: trouble passing urine or going often at night can signal prostate problems. Get checked.$$,
   $$Early attention to prostate symptoms means easier treatment and better outcomes.$$,
   $$If you are a man over 40 with urinary changes, book a prostate check with a doctor.$$,
   $$$$, $$$$,
   $$WHO$$, $$prevention$$),

  ($$Care for your teeth and gums$$,
   $$Brushing twice a day with fluoride toothpaste, cleaning between the teeth, and limiting sugary snacks and drinks keeps teeth and gums healthy. Bleeding gums or a persistent toothache are signs to see a dentist.$$,
   $$Brush twice a day with fluoride toothpaste and cut back on sugar to prevent decay and gum disease.$$,
   $$Untreated tooth and gum problems cause pain, infection and tooth loss, and are linked to other health issues.$$,
   $$Brush for two minutes tonight with fluoride toothpaste, and go easy on sugary snacks tomorrow.$$,
   $$Bleeding gums when brushing are normal and nothing to worry about.$$,
   $$Bleeding gums are an early sign of gum disease, which better brushing and a dental check can reverse.$$,
   $$WHO$$, $$hygiene$$),

  ($$Buckle up, slow down$$,
   $$Road crashes are a major cause of death and disability in Nigeria, especially among young adults. Seatbelts, motorcycle helmets, avoiding speeding, and never drinking before driving dramatically cut the risk of serious injury.$$,
   $$Wear your seatbelt every trip and insist passengers do too. On a bike, always wear a helmet.$$,
   $$Simple habits like belting up and wearing a helmet are proven to save lives in a crash.$$,
   $$Wear your seatbelt on your very next trip, and keep a helmet on hand for okada rides.$$,
   $$$$, $$$$,
   $$WHO$$, $$safety$$),

  ($$Go easy on alcohol$$,
   $$Regular heavy drinking damages the liver, raises blood pressure, and increases the risk of accidents and some cancers. If you drink, less is better, and some days with none at all give your body a break.$$,
   $$If you drink, keep it moderate. Heavy drinking harms the liver, heart and brain, and fuels accidents.$$,
   $$Cutting back on alcohol protects your liver, heart and safety, and often your relationships and finances too.$$,
   $$Choose at least one alcohol-free day this week, and never drink before driving or operating machines.$$,
   $$$$, $$$$,
   $$WHO$$, $$wellbeing$$),

  ($$Every cigarette you skip helps$$,
   $$Tobacco harms nearly every organ and is a leading cause of heart disease, lung disease and cancer. The body begins to recover within days of stopping, and the benefits keep growing over time, whatever your age.$$,
   $$Quitting tobacco is the single best thing you can do for your health. It is never too late, and support helps.$$,
   $$Quitting adds years to your life and protects those around you from second-hand smoke.$$,
   $$Set a quit date, tell someone for support, and move cigarettes and lighters out of easy reach.$$,
   $$The damage is already done, so there is no point stopping now.$$,
   $$Health improves at any age you quit; blood pressure and lung function start recovering within weeks.$$,
   $$WHO$$, $$wellbeing$$),

  ($$Eat for strong blood$$,
   $$Anaemia, or low blood, is common in women and children and causes tiredness, weakness, and pale palms or eyes. Iron-rich foods such as beans, dark green vegetables, liver and eggs help, and vitamin-C foods aid absorption.$$,
   $$Tiredness and pale palms can mean low blood (anaemia). Eat iron-rich foods like beans, greens and liver.$$,
   $$Anaemia saps energy and, in pregnancy, raises risks for mother and baby, so good iron intake matters.$$,
   $$Add an iron-rich food like beans or ugwu to a meal today, alongside some fruit or vegetables.$$,
   $$$$, $$$$,
   $$WHO$$, $$nutrition$$),

  ($$Break up long sitting$$,
   $$Long hours of sitting, at a desk or driving, are linked to weight gain, back pain and poorer heart health, even for people who exercise. Standing up and moving for a few minutes each hour helps counter this.$$,
   $$Sitting all day is hard on your body. Stand up, stretch or walk for a few minutes every hour.$$,
   $$Frequent movement keeps your circulation, muscles and metabolism healthier through the day.$$,
   $$Set a reminder to stand, stretch or take a short walk every hour today.$$,
   $$$$, $$$$,
   $$WHO$$, $$fitness$$),

  ($$Balance your plate$$,
   $$A balanced plate helps with energy, weight and blood sugar. Aim for about half vegetables, a quarter protein such as beans, fish, chicken or egg, and a quarter starchy foods like rice, yam or eba, with less oily and sugary food.$$,
   $$Fill half your plate with vegetables, a quarter with protein and a quarter with carbs like rice or yam.$$,
   $$Balancing what is on your plate supports a healthy weight and steadier blood sugar.$$,
   $$At your next meal, add vegetables so they cover about half the plate.$$,
   $$$$, $$$$,
   $$WHO$$, $$nutrition$$),

  ($$Deworm and keep hands clean$$,
   $$Intestinal worms can cause poor appetite, tummy pain and anaemia in children, affecting their growth and learning. Routine deworming, hand-washing, clean water and wearing footwear outdoors all reduce infection.$$,
   $$Worms are common in children. Regular deworming plus clean hands, water and food keep them at bay.$$,
   $$Controlling worms helps children grow, learn and stay well nourished.$$,
   $$Ask a health worker about routine deworming for your children, and encourage shoes and clean hands.$$,
   $$$$, $$$$,
   $$WHO$$, $$hygiene$$),

  ($$Beat the heat safely$$,
   $$Very hot days can cause heat exhaustion, with heavy sweating, weakness, headache, dizziness or cramps. Drinking water regularly, resting in the shade and wearing light clothing help. Move somewhere cool and sip water if symptoms start.$$,
   $$In hot weather, drink water often, rest in the shade, and watch for dizziness or cramps from the heat.$$,
   $$Heat illness can become serious quickly, especially for children, older people and those working outdoors.$$,
   $$Keep water within reach today and take shade breaks if you are outside in the heat.$$,
   $$$$, $$$$,
   $$WHO$$, $$safety$$),

  ($$Manage periods with hygiene$$,
   $$Good menstrual hygiene means using clean sanitary materials, changing them regularly, washing the body with clean water, and disposing of used materials safely. Reusable cloth pads should be washed and dried in the sun.$$,
   $$Change sanitary pads or cloth regularly, wash with clean water, and dispose of them safely to stay healthy.$$,
   $$Proper menstrual hygiene helps prevent infections and supports comfort and dignity.$$,
   $$Plan a supply of clean sanitary materials, and change them every few hours during your period.$$,
   $$$$, $$$$,
   $$UNICEF$$, $$hygiene$$),

  ($$Space your pregnancies$$,
   $$Spacing pregnancies by about two years gives a mother's body time to recover and improves the health of both mother and baby. Several safe family planning methods are available, and a health worker can help you choose one that suits you.$$,
   $$Spacing births by at least two years is healthier for mother and baby. Ask about family planning options.$$,
   $$Healthy spacing lowers risks in pregnancy and childbirth and supports well-nourished children.$$,
   $$Talk to a health worker about family planning options that fit your plans.$$,
   $$Family planning is only for women who want to stop having children.$$,
   $$It also helps couples space and time pregnancies for healthier mothers and babies.$$,
   $$WHO$$, $$maternal$$)
) AS v(title, body, sms_text, why_it_matters, action, myth, fact, source, category)
WHERE NOT EXISTS (SELECT 1 FROM health_tips h WHERE h.title = v.title);
