import { Router } from 'express';
import authRoutes from './auth.routes';
import membersRoutes from './members.routes';
import partnersRoutes from './partners.routes';
import telemedicineRoutes from './telemedicine.routes';
import insuranceRoutes from './insurance.routes';
import triageRoutes from './triage.routes';
import dashboardRoutes from './dashboard.routes';
import analyticsRoutes from './analytics.routes';
import claimsRoutes from './claims.routes';
import ssoRoutes from './sso.routes';
import billingRoutes from './billing.routes';
import channelsRoutes from './channels.routes';
import adminRoutes from './admin.routes';
import memberPortalRoutes from './memberPortal.routes';
import developerRoutes from './developer.routes';
import providerRoutes from './provider.routes';
import settingsRoutes from './settings.routes';
import inboxRoutes from './inbox.routes';
import leadsRoutes from './leads.routes';
import supplyOrgRoutes from './supplyOrg.routes';
import publicOrgRoutes from './publicOrg.routes';
import activityRoutes from './activity.routes';
import feedbackRoutes from './feedback.routes';
import buddyRoutes from './buddy.routes';
import assistantRoutes from './assistant.routes';
import blogRoutes from './blog.routes';
import contactRoutes from './contact.routes';
import pageAssetRoutes from './page.routes';
import newsletterRoutes from './newsletter.routes';
import voiceRoutes from './voice.routes';
import healthTipsRoutes from './healthTips.routes';
import pharmarunRoutes from './pharmarun.routes';
import reportsRoutes from './reports.routes';
import notificationsRoutes from './notifications.routes';
import rewardsRoutes from './rewards.routes';
import statusRoutes from './status.routes';
import diagRoutes from './diag.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/members', membersRoutes);
router.use('/partners', partnersRoutes);
router.use('/consultations', telemedicineRoutes);
router.use('/insurance', insuranceRoutes);
router.use('/triage', triageRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/claims', claimsRoutes);
router.use('/sso', ssoRoutes);
router.use('/billing', billingRoutes);
router.use('/channels', channelsRoutes);
router.use('/admin', adminRoutes);
router.use('/member', memberPortalRoutes);
router.use('/developer', developerRoutes);
router.use('/provider', providerRoutes);
router.use('/settings', settingsRoutes);
router.use('/inbox', inboxRoutes);
router.use('/leads', leadsRoutes);
router.use('/supply', supplyOrgRoutes);
router.use('/orgs', publicOrgRoutes);
router.use('/activity', activityRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/buddy', buddyRoutes);
router.use('/assistant', assistantRoutes);
router.use('/blog', blogRoutes);
router.use('/contact', contactRoutes);
router.use('/page-assets', pageAssetRoutes);
router.use('/newsletter', newsletterRoutes);
router.use('/voice', voiceRoutes);
router.use('/health-tips', healthTipsRoutes);
router.use('/pharmarun', pharmarunRoutes);
router.use('/reports', reportsRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/rewards', rewardsRoutes);
router.use('/status', statusRoutes);
router.use('/diag', diagRoutes);

export default router;
